In [1]:
import numpy as np


In [2]:
# Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

v_1 = np.arange(1, 11)
print(v_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

m_1 = np.zeros((3, 3))
print(m_1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# Створення масиву розміром 5x5 з випадковими цілими числами в діапазоні від 1 до 10

m_2 = np.random.randint(1, 11, (5, 5))
print(m_2)

[[9 7 7 1 7]
 [1 6 6 4 7]
 [2 9 1 3 2]
 [6 4 4 2 3]
 [8 7 6 2 8]]


In [5]:
# Створення масиву розміром 4x4 з випадковими дійсними числами в діапазоні від 0 до 1

m_3 = np.random.rand(4, 4)
print(m_3)

[[0.62467292 0.85939236 0.3250813  0.44926985]
 [0.26838997 0.95499297 0.2694244  0.69786986]
 [0.70235124 0.65948817 0.81433742 0.72339435]
 [0.87449926 0.79040788 0.3638972  0.04733518]]


In [7]:
# Створення двох одновимірних масивів розміром 5 з випадковими цілими числами в діапазоні від 1 до 10

v_2 = np.random.randint(1, 11, 5)
v_3 = np.random.randint(1, 11, 5)
print(v_2)
print(v_3)

[ 7 10  6  6  1]
[6 9 8 9 2]


In [8]:
# Поелементні операції додавання, віднімання та множення

add = np.add(v_2, v_3)
subtract = np.subtract(v_2, v_3)
multiply = np.multiply(v_2, v_3)
print(add)
print(subtract)
print(multiply)

[13 19 14 15  3]
[ 1  1 -2 -3 -1]
[42 90 48 54  2]


In [9]:
# Створення двох векторів розміром 7 з довільними числами

v_4 = np.random.randint(1, 11, 7)
v_5 = np.random.randint(1, 11, 7)
print(v_4)
print(v_5)

[6 1 1 6 7 9 8]
[ 2 10 10  7  2  7  5]


In [10]:
# Знаходження скалярного добутку

dot_product = np.dot(v_4, v_5)
print(dot_product)

191


In [11]:
# Створення двох матриць розміром 2x2 та 2x3 з випадковими цілими числами

m_4 = np.random.randint(1, 11, (2, 2))
m_5 = np.random.randint(1, 11, (2, 3))
print(m_4)
print(m_5)

[[5 2]
 [9 1]]
[[3 2 6]
 [1 8 4]]


In [12]:
# Перемноження матриць

m_multiply = np.dot(m_4, m_5)
print(m_multiply)

[[17 26 38]
 [28 26 58]]
