In [5]:
import numpy as np


In [2]:
# Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

v_1 = np.arange(1, 11)
print(v_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

m_1 = np.zeros((3, 3))
print(m_1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# Створення масиву розміром 5x5 з випадковими цілими числами в діапазоні від 1 до 10

m_2 = np.random.randint(1, 11, (5, 5))
print(m_2)

[[9 7 7 1 7]
 [1 6 6 4 7]
 [2 9 1 3 2]
 [6 4 4 2 3]
 [8 7 6 2 8]]


In [5]:
# Створення масиву розміром 4x4 з випадковими дійсними числами в діапазоні від 0 до 1

m_3 = np.random.rand(4, 4)
print(m_3)

[[0.62467292 0.85939236 0.3250813  0.44926985]
 [0.26838997 0.95499297 0.2694244  0.69786986]
 [0.70235124 0.65948817 0.81433742 0.72339435]
 [0.87449926 0.79040788 0.3638972  0.04733518]]


In [7]:
# Створення двох одновимірних масивів розміром 5 з випадковими цілими числами в діапазоні від 1 до 10

v_2 = np.random.randint(1, 11, 5)
v_3 = np.random.randint(1, 11, 5)
print(v_2)
print(v_3)

[ 7 10  6  6  1]
[6 9 8 9 2]


In [8]:
# Поелементні операції додавання, віднімання та множення

add = np.add(v_2, v_3)
subtract = np.subtract(v_2, v_3)
multiply = np.multiply(v_2, v_3)
print(add)
print(subtract)
print(multiply)

[13 19 14 15  3]
[ 1  1 -2 -3 -1]
[42 90 48 54  2]


In [9]:
# Створення двох векторів розміром 7 з довільними числами

v_4 = np.random.randint(1, 11, 7)
v_5 = np.random.randint(1, 11, 7)
print(v_4)
print(v_5)

[6 1 1 6 7 9 8]
[ 2 10 10  7  2  7  5]


In [10]:
# Знаходження скалярного добутку

dot_product = np.dot(v_4, v_5)
print(dot_product)

191


In [11]:
# Створення двох матриць розміром 2x2 та 2x3 з випадковими цілими числами

m_4 = np.random.randint(1, 11, (2, 2))
m_5 = np.random.randint(1, 11, (2, 3))
print(m_4)
print(m_5)

[[5 2]
 [9 1]]
[[3 2 6]
 [1 8 4]]


In [12]:
# Перемноження матриць

m_multiply = np.dot(m_4, m_5)
print(m_multiply)

[[17 26 38]
 [28 26 58]]


In [6]:
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

m_6 = np.random.randint(1, 11, (3, 3))
print(m_6)

inverse_m_6 = np.linalg.inv(m_6)
print(inverse_m_6)



[[9 8 9]
 [5 1 9]
 [7 6 9]]
[[ 0.83333333  0.33333333 -1.16666667]
 [-0.33333333 -0.33333333  0.66666667]
 [-0.42592593 -0.03703704  0.57407407]]


In [7]:
# Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

m_7 = np.random.rand(4, 4)
print(m_7)

transposed_m_7 = np.transpose(m_7)
print(transposed_m_7)

[[0.34374534 0.62101709 0.84880215 0.47810231]
 [0.50520479 0.2753544  0.21742023 0.80157248]
 [0.75716238 0.08364324 0.67319584 0.1668308 ]
 [0.32152012 0.33593795 0.08148983 0.60928235]]
[[0.34374534 0.50520479 0.75716238 0.32152012]
 [0.62101709 0.2753544  0.08364324 0.33593795]
 [0.84880215 0.21742023 0.67319584 0.08148983]
 [0.47810231 0.80157248 0.1668308  0.60928235]]


In [8]:
# Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

m_10 = np.random.randint(1, 11, (3, 4))
print(m_10)

v_10 = np.random.randint(1, 11, 4)
print(v_10)

result = np.dot(m_10, v_10)
print(result)

[[10  7  2  3]
 [ 3  6  4  6]
 [ 4  8 10  8]]
[1 4 6 8]
[ 74  99 160]


In [9]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

import numpy as np

m_11 = np.random.rand(2, 3)
print(m_11)

v_11 = np.random.rand(3)
print(v_11)

result = np.dot(m_11, v_11)
print(result)


[[0.03208528 0.31372114 0.21284084]
 [0.82792789 0.61456935 0.72640556]]
[0.52823478 0.6860968  0.6362192 ]
[0.36760505 1.32114754]


In [10]:
# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

m_12_1 = np.random.randint(1, 11, (2, 2))
m_12_2 = np.random.randint(1, 11, (2, 2))

print(m_12_1)
print(m_12_2)

result = np.multiply(m_12_1, m_12_2)
print(result)

[[10  2]
 [ 3  5]]
[[2 9]
 [7 6]]
[[20 18]
 [21 30]]


In [11]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

m_13_1 = np.random.randint(1, 11, (2, 2))
m_13_2 = np.random.randint(1, 11, (2, 2))

print(m_13_1)
print(m_13_2)

result = np.dot(m_13_1, m_13_2)

print(result)

[[8 1]
 [8 5]]
[[7 7]
 [6 6]]
[[62 62]
 [86 86]]


In [12]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

m_14 = np.random.randint(1, 101, (5, 5))
print(m_14)

sum_m = np.sum(m_14)
print(sum_m)

[[81 15 35 10 88]
 [ 3  5 63  6 63]
 [54 42 89 56 35]
 [70 75  6 74 11]
 [59 76 90 98 23]]
1227


In [13]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

m_15_1 = np.random.randint(1, 11, (4, 4))
m_15_2 = np.random.randint(1, 11, (4, 4))
print(m_15_1)
print(m_15_2)

difference_m = m_15_1 - m_15_2
print(difference_m)

[[ 9  1  5  6]
 [ 9  6  6  2]
 [ 7  7  5  4]
 [ 7  6 10  9]]
[[ 2  7  4  1]
 [ 3  8  9 10]
 [10  1  9  2]
 [ 2  8 10  1]]
[[ 7 -6  1  5]
 [ 6 -2 -3 -8]
 [-3  6 -4  2]
 [ 5 -2  0  8]]


In [14]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

m_16 = np.random.rand(3, 3)
print(m_16)

row_sum_vector = np.sum(m_16, axis=1)
print(row_sum_vector)

[[0.66444634 0.09111154 0.72628083]
 [0.63154679 0.37098827 0.40163644]
 [0.14138505 0.9298201  0.23448725]]
[1.48183872 1.4041715  1.3056924 ]


In [15]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

m_17 = np.random.randint(1, 11, (3, 4))
print(m_17)

squared_m_17 = np.square(m_17)
print(squared_m_17)

[[ 5  2 10  8]
 [ 6  2  2  7]
 [ 8  6  9  7]]
[[ 25   4 100  64]
 [ 36   4   4  49]
 [ 64  36  81  49]]


In [16]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

v_18 = np.random.randint(1, 51, 4)
print(v_18)

sqrt_v_18 = np.sqrt(v_18)
print(sqrt_v_18)

[19  1  6 26]
[4.35889894 1.         2.44948974 5.09901951]
